services:
  frogrock:
    build: .
    container_name: frogrock
    env_file: .env
    ports:
      - "${PORT:-8090}:8090"
    volumes:
      - "${HOST_CACHE_DIR}:/cache"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
